name: Update Signals

on:
  schedule:
    - cron: '0 */3 * * *'  # 每3小时自动运行
  workflow_dispatch:       # 允许手动运行

jobs:
  update-signals:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run signal script
        run: python mstz_quant_signal.py

      - name: Commit & Push Changes
        run: |
          git config user.name "kenny2000j12"
          git config user.email "kenny2000j12@users.noreply.github.com"
          git add trade_signals.json
          git commit -m "Auto update trade signals" || echo "No changes to commit"
          git push https://kenny2000j12:${{ secrets.GH_TOKEN }}@github.com/kenny2000j12/mstz-dashboard.git HEAD:main
