name: Update Signals

on:
  schedule:
    - cron: '*/15 * * * *'  # 每15分钟运行一次
  workflow_dispatch:

jobs:
  update-signals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run signal script
        run: |
          python mstw_quant_signal.py

      - name: Commit & Push Changes
        run: |
          git config user.name "kenny2000j12"
          git config user.email "kenny2000j12@users.noreply.github.com"
          git add trade_signals.json || echo "Nothing to add"
          git commit -m "Auto update trade signals" || echo "Nothing to commit"
          git push || echo "Push failed, maybe no change or permission issue"
