name: Update Signals

on:
  schedule:
    - cron: '0 13 * * *'  # 每天 21:00（北京时间）运行
  workflow_dispatch:       # 支持手动运行

jobs:
  update-signals:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install --upgrade pip

      - name: Run Signal Script
        run: python mstz_quant_signal.py

      - name: Commit Updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add trade_signals.json
          git commit -m "Auto update trade signals" || echo "No changes to commit"
          git push https://kenny2000j12:${{ secrets.GH_TOKEN }}@github.com/kenny2000j12/mstz-dashboard.git HEAD:main
