name: Update Signals

on:
  schedule:
    - cron: '30 13 * * *'  # 每天北京时间21:30 运行（13:30 UTC）
  workflow_dispatch:        # 手动触发

jobs:
  update-signals:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Signal Script
        run: python mstz_quant_signal.py

      - name: Commit Updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add signals.json
          git commit -m "Auto update trade signals" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/kenny2000j12/mstz-dashboard.git HEAD:main
