
name: Update Quant Signal Every 2 Minutes

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  update-signal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install yfinance pandas
      - name: Run quant script
        run: python mstz_quant_signal.py
      - name: Commit and push
        run: |
          git config --global user.name "MSTZ Bot"
          git config --global user.email "bot@example.com"
          git add trade_signals.json
          git commit -m "Auto update signal"
          git push
