name: Update Trading Signals

on:
  schedule:
    - cron: '*/2 * * * *'  # 每2分钟执行一次（可根据需求更改）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance ta pandas

      - name: Run signal generator
        run: python generate_signals.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add trade_signal.json
          git commit -m "Auto update trade signals" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
