name: Update Trading Signals

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install yfinance pandas

    - name: Generate signals
      run: python generate_signals.py

    - name: Commit and push
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add trade_signals.json
        git commit -m "Auto update trade signals" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
